server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://tasker-db.cqb1gguuidpm.ap-northeast-2.rds.amazonaws.com:3306/dev_tasker?useSSL=false
    autoReconnect: true
    username: ENC(nVtTu8E0lIFlhIiEg3AxEQ==)
    password: ENC(jY5SEnUXi3NUs1eFwOsi8amZcUrNH1on)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    initialize: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    path match:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true


  jwt:
    access-key: ENC(RjPKYht6ej5GPEvbNQjdYMs+VUDjtJZD2rsApw0zDEA=)
    refresh-key: ENC(m6i3WcLTHVxa9lPj0X/90eS/NIFMJmKI51LKnB1cqPU5/FKqXo2jFA==)


cloud:
  aws:
    s3:
      bucket: tasker-bucket
    credentials:
      instanceProfile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false

sms:
  service-id: ENC(b5fm616DK5BsXZ7WRW6UjCNjEK9PXumKOZ45fDaHMMK1q7i30mQ8XA==)
  access-key: ENC(9bAnKJiVlwT+p1Uirtu5hzqJVrM6sJcw+kS61QiOPro=)
  secret-key: ENC(0isPpL5NVvmekDE6whE73CD3rGTxLzL673sm+OZL66aLRk8IfM5azL8VhICy9fjHsPvam6X/3No=)

jasypt:
  encryptor:
    bean: jasyptEncyptor
